model:
  name: "cardiffnlp/twitter-roberta-base-sentiment-latest"
  max_length: 128

inference:
  device: "auto"
  batch_size: 32
  seed: 42

data:
  data_dir: "src/datasets/test_data"
  input_file: "test_data.txt"
  output_dir: "data/predictions"
  output_file: "sentiment_predictions.csv"